language: go

go:
  - tip
  - 1.15

before_install:
  - sudo apt-get -qq install libdevmapper-dev libseccomp2 libseccomp-dev

script:
  - make build
  - make install.tools
  - make validate
  - make vendor
  - make test
